### ISSUE TITLE
Problem: Enduro does not work if no standard transfer source is configured

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#7]
**Current situation**
I am running Enduro with the following watcher/pipeline configuration:

```shell
[[watcher.filesystem]]
name = "file-drop"
path = "/eos/workspace/o/oais/archivematica-qa/file-drop/"
pipeline = "am"

[[pipeline]]
name = "am"
baseURL = "http://archivematica-dashboard-dev.cern.ch"
user = "archivematica"
key = "ac3b3f2d25ea11c616a16adf1ca6953ad73f3645"
transferLocationID = "fa3bc639-f645-4080-8fc8-b37c1545152b"
transferDir = "/eos/workspace/o/oais/archivematica-qa/storage-dev/enduro"
```

In my storage service I have several transfer sources, but no default transfer source:
![image](https://user-images.githubusercontent.com/7934339/68138941-99c3d180-ff29-11e9-8af8-b536336f259f.png)

When I copy a file to the watched directory, Enduro correctly picks up this change and starts a new transfer workflow. However, this workflow never finishes. Looking in my MCP Server logs I find the following:

```shell
DEBUG     2019-11-04 16:40:15  archivematica.mcp.server:package:create_package:315:  Transfer object created: a2727dad-dab1-423f-9bf1-04482c39b982
DEBUG     2019-11-04 16:40:15  archivematica.mcp.server:package:_start:325:  Package a2727dad-dab1-423f-9bf1-04482c39b982: starting transfer (('694781501', u'standard', 'c/694781501', '/cephfs/sharedDirectory/tmp/tmpy1tmGR'))
DEBUG     2019-11-04 16:40:15  archivematica.mcp.server:package:_start_package_transfer_with_auto_approval:409:  Package a2727dad-dab1-423f-9bf1-04482c39b982: determined vars transfer_rel=tmp/tmpy1tmGR/694781501, filepath=/cephfs/sharedDirectory/tmp/tmpy1tmGR/694781501, path=c/694781501/.
DEBUG     2019-11-04 16:40:15  archivematica.mcp.server:package:_start_package_transfer_with_auto_approval:416:  Package a2727dad-dab1-423f-9bf1-04482c39b982: copying chosen contents from transfer sources (from=c/694781501/., to=tmp/tmpy1tmGR/694781501)
DEBUG     2019-11-04 16:40:15  archivematica.common:storageService:get_location:192:  Storage locations returned: [{u'uuid': u'6183e935-2fdd-4e47-921d-5439a3e3bc10', u'pipeline': [u'/api/v2/pipeline/e4866b3a-a905-442f-879b-db6312bedb21/'], u'used': u'0', u'description': u'Cephfs shared directory', u'space': u'/api/v2/space/6963fccb-562d-4e4f-a858-2b57b6aa9bcb/', u'enabled': True, u'quota': None, u'relative_path': u'/cephfs/sharedDirectory/', u'purpose': u'CP', u'path': u'/cephfs/sharedDirectory', u'resource_uri': u'/api/v2/location/6183e935-2fdd-4e47-921d-5439a3e3bc10/'}]
DEBUG     2019-11-04 16:40:15  archivematica.common:storageService:get_location:192:  Storage locations returned: [{u'uuid': u'4b24d979-548f-4b75-b3ee-9baf3362d412', u'pipeline': [u'/api/v2/pipeline/e4866b3a-a905-442f-879b-db6312bedb21/'], u'used': u'0', u'description': u'SampleTransfers', u'space': u'/api/v2/space/6963fccb-562d-4e4f-a858-2b57b6aa9bcb/', u'enabled': True, u'quota': None, u'relative_path': u'/eos/home-j/jorkemen/archivematica-sampledata/SampleTransfers/', u'purpose': u'TS', u'path': u'/eos/home-j/jorkemen/archivematica-sampledata/SampleTransfers', u'resource_uri': u'/api/v2/location/4b24d979-548f-4b75-b3ee-9baf3362d412/'}, {u'uuid': u'1872a0a1-e775-4a2f-b3af-f5caaa85b77e', u'pipeline': [u'/api/v2/pipeline/e4866b3a-a905-442f-879b-db6312bedb21/'], u'used': u'0', u'description': u'TestTransfers', u'space': u'/api/v2/space/6963fccb-562d-4e4f-a858-2b57b6aa9bcb/', u'enabled': True, u'quota': None, u'relative_path': u'/eos/home-j/jorkemen/archivematica-sampledata/TestTransfers/', u'purpose': u'TS', u'path': u'/eos/home-j/jorkemen/archivematica-sampledata/TestTransfers', u'resource_uri': u'/api/v2/location/1872a0a1-e775-4a2f-b3af-f5caaa85b77e/'}, {u'uuid': u'1cd9fc80-4257-4a66-bbe2-53f4b98f0f05', u'pipeline': [u'/api/v2/pipeline/e4866b3a-a905-442f-879b-db6312bedb21/'], u'used': u'0', u'description': u'', u'space': u'/api/v2/space/6963fccb-562d-4e4f-a858-2b57b6aa9bcb/', u'enabled': True, u'quota': None, u'relative_path': u'/eos/home-j/jorkemen/JPEGicon1440/', u'purpose': u'TS', u'path': u'/eos/home-j/jorkemen/JPEGicon1440', u'resource_uri': u'/api/v2/location/1cd9fc80-4257-4a66-bbe2-53f4b98f0f05/'}, {u'uuid': u'fa3bc639-f645-4080-8fc8-b37c1545152b', u'pipeline': [u'/api/v2/pipeline/e4866b3a-a905-442f-879b-db6312bedb21/'], u'used': u'0', u'description': u'Enduro source', u'space': u'/api/v2/space/6963fccb-562d-4e4f-a858-2b57b6aa9bcb/', u'enabled': True, u'quota': None, u'relative_path': u'/eos/workspace/o/oais/archivematica-qa/storage-dev/enduro', u'purpose': u'TS', u'path': u'/eos/workspace/o/oais/archivematica-qa/storage-dev/enduro', u'resource_uri': u'/api/v2/location/fa3bc639-f645-4080-8fc8-b37c1545152b/'}]
ERROR     2019-11-04 16:40:15  archivematica.mcp.server:package:wrap:371:  Exception: 404 Client Error: NOT FOUND for url: http://archivematica-storage-dev.cern.ch/api/v2/location/default/TS/
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPServer/package.py", line 350, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/archivematica/MCPServer/package.py", line 418, in _start_package_transfer_with_auto_approval
    _copy_from_transfer_sources([path], transfer_rel)
  File "/usr/lib/archivematica/MCPServer/package.py", line 192, in _copy_from_transfer_sources
    location = _default_transfer_source_location_uuid()
  File "/usr/lib/archivematica/MCPServer/package.py", line 170, in _default_transfer_source_location_uuid
    location = storage_service.get_default_location("TS")
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 199, in get_default_location
    response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://archivematica-storage-dev.cern.ch/api/v2/location/default/TS/
```

As far as I understand there is a problem with the paths of the created transfer. The directory of my transfer, `c/694781501`, is a relative path that does not include the UUID of the transfer location. This causes the MCP Server to use the default transfer source, but since I don't have a default transfer source the copy fails. 

**Possible solutions**
I am not completely sure about the possible solutions. But I have a hunch that we need to update the [amclient package endpoint](https://github.com/artefactual-labs/enduro/blob/3bbd48a88dc0cdb4f00fe9dbef63a22f4900bf15/internal/amclient/v2_package.go#L37) to include the transfer source. At least this is what I use in my own [api calls](https://gist.github.com/jorikvankemenade/7f63b5749f4c07d7ae5e7fe24b47732c#file-automatic-ingest-py-L16) when using the [python client](https://github.com/artefactual-labs/amclient/blob/cb9a5961d38d72da18955a7fdc05df77be344476/amclient/amclient.py#L555). 

Please let me know what you think the cause of this issue is. It might very well be a misconfiguration on my side. And what you think of the proposed solution.

**Environment**
Latest Enduro, Archivematica 1.10 on CentOS 7.

**Comment by sevein** [comment]
@jorikvankemenade, are you running v0.3.0 or newer? If so, transferLocationID should be incorporated to the path string that we send to Archivematica (see https://git.io/Je22G).

**Comment by jorikvankemenade** [comment]
@sevein no I am still on v0.2.1, I'll update my install first thing tomorrow and test again!

**Comment by jorikvankemenade** [comment]
Yes, updating to v0.4.0 fixed the issues for me. Thank you for responding so fast, in the future I will first check the new releases :).
